# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_pk', models.IntegerField(unique=True)),
                ('link', models.CharField(max_length=400)),
                ('game_type', models.CharField(max_length=10)),
                ('season', models.IntegerField()),
                ('game_date', models.DateTimeField()),
                ('status_code', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('home_score', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=400)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('primary_number', models.CharField(max_length=200, null=True)),
                ('birth_date', models.DateTimeField()),
                ('current_age', models.IntegerField()),
                ('birth_city', models.CharField(max_length=200)),
                ('birth_state_province', models.CharField(max_length=200)),
                ('birth_country', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField(default=0)),
                ('active', models.BooleanField()),
                ('alternate_captain', models.BooleanField()),
                ('captain', models.BooleanField()),
                ('rookie', models.BooleanField()),
                ('shoots_catches', models.CharField(max_length=10)),
                ('roster_status', models.CharField(max_length=10)),
                ('primary_position_abbr', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('first_year_of_play', models.IntegerField()),
                ('official_site_url', models.CharField(max_length=200)),
                ('division_id', models.IntegerField()),
                ('conference_id', models.IntegerField()),
                ('franchise_id', models.IntegerField()),
                ('short_name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='playergame',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Team'),
        ),
        migrations.AddField(
            model_name='playergame',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_team', to='lineups.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_team', to='lineups.Team'),
        ),
    ]
