# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0002_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_on_ice', models.CharField(max_length=50)),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('power_play_goals', models.IntegerField()),
                ('power_player_assists', models.IntegerField()),
                ('penalty_minutes', models.CharField(max_length=50)),
                ('faceoff_wins', models.IntegerField()),
                ('faceoff_taken', models.IntegerField()),
                ('takeaways', models.IntegerField()),
                ('giveaways', models.IntegerField()),
                ('short_handed_goals', models.IntegerField()),
                ('short_handed_assists', models.IntegerField()),
                ('blocked', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('even_time_on_ice', models.CharField(max_length=50)),
                ('power_play_time_on_ice', models.CharField(max_length=50)),
                ('short_handed_time_on_ice', models.CharField(max_length=50)),
                ('saves', models.IntegerField()),
                ('power_play_saves', models.IntegerField()),
                ('short_handed_saves', models.IntegerField()),
                ('even_saves', models.IntegerField()),
                ('short_handed_shots_against', models.IntegerField()),
                ('power_play_shots_against', models.IntegerField()),
                ('decision', models.CharField(max_length=50)),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.PlayerGame')),
            ],
        ),
    ]
