# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0003_playergamestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='shots_against',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
