# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0004_playergamestats_shots_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_state_province',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
