# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0005_auto_20161220_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='alternate_captain',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='captain',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_age',
            field=models.IntegerField(null=True),
        ),
    ]
