# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0007_auto_20161220_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestats',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='even_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='even_time_on_ice',
            field=models.CharField(default='0:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='faceoff_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='faceoff_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='giveaways',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='penalty_minutes',
            field=models.CharField(default='0:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='plus_minus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='power_play_assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='power_play_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='power_play_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='power_play_shots_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='power_play_time_on_ice',
            field=models.CharField(default='0:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='short_handed_assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='short_handed_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='short_handed_saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='short_handed_shots_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='short_handed_time_on_ice',
            field=models.CharField(default='0:00', max_length=50),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='shots_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='takeaways',
            field=models.IntegerField(default=0),
        ),
    ]
