# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0008_auto_20161220_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='even_shots_against',
            field=models.IntegerField(default=0),
        ),
    ]
