# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0009_playergamestats_even_shots_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lineups.Team'),
        ),
    ]
