# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0010_auto_20161220_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shoots_catches',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
