# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0011_auto_20161220_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOdds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_money_line', models.CharField(max_length=50)),
                ('home_probability', models.FloatField()),
                ('away_money_line', models.CharField(max_length=50)),
                ('away_probability', models.FloatField()),
                ('number_of_goals', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Game')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameExpectedStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.FloatField(default=0.0)),
                ('assists', models.FloatField(default=0.0)),
                ('shotsOnGoal', models.FloatField(default=0.0)),
                ('blockedShots', models.FloatField(default=0.0)),
                ('shortHandedPoints', models.FloatField(default=0.0)),
                ('shootoutGoals', models.FloatField(default=0.0)),
                ('hatTricks', models.FloatField(default=0.0)),
                ('wins', models.FloatField(default=0.0)),
                ('saves', models.FloatField(default=0.0)),
                ('goalsAgainst', models.FloatField(default=0.0)),
                ('shutouts', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.PlayerGame')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.FloatField(default=0.0)),
                ('actual_value', models.FloatField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.PlayerGame')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonId', models.IntegerField()),
                ('gamesPlayed', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('otLosses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('regPlusOtWins', models.IntegerField()),
                ('pointPctg', models.FloatField()),
                ('goalsFor', models.IntegerField()),
                ('goalsAgainst', models.IntegerField()),
                ('goalsForPerGame', models.FloatField()),
                ('goalsAgainstPerGame', models.FloatField()),
                ('ppPctg', models.FloatField()),
                ('pkPctg', models.FloatField()),
                ('shotsForPerGame', models.FloatField()),
                ('shotsAgainstPerGame', models.FloatField()),
                ('faceoffWinPctg', models.FloatField()),
                ('goalsAgainstPerGamePercentage', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lineups.Team')),
            ],
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
