# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0012_auto_20161220_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='blockedShots',
            new_name='blocked_shots',
        ),
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='goalsAgainst',
            new_name='goals_against',
        ),
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='hatTricks',
            new_name='hat_tricks',
        ),
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='shootoutGoals',
            new_name='shootout_goals',
        ),
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='shortHandedPoints',
            new_name='short_handed_points',
        ),
        migrations.RenameField(
            model_name='playergameexpectedstats',
            old_name='shotsOnGoal',
            new_name='shots_on_goal',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='faceoffWinPctg',
            new_name='faceoff_win_pctg',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='gamesPlayed',
            new_name='games_played',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='goalsAgainst',
            new_name='goals_against',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='goalsAgainstPerGame',
            new_name='goals_against_per_game',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='goalsAgainstPerGamePercentage',
            new_name='goals_against_per_game_percentage',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='goalsFor',
            new_name='goals_for',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='goalsForPerGame',
            new_name='goals_for_per_game',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='otLosses',
            new_name='ot_losses',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='pkPctg',
            new_name='pk_pctg',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='pointPctg',
            new_name='point_pctg',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='ppPctg',
            new_name='pp_pctg',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='regPlusOtWins',
            new_name='reg_plus_ot_wins',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='seasonId',
            new_name='season_id',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='shotsAgainstPerGame',
            new_name='shots_against_per_game',
        ),
        migrations.RenameField(
            model_name='teamstats',
            old_name='shotsForPerGame',
            new_name='shots_for_per_game',
        ),
    ]
