# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0013_auto_20161220_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstats',
            name='goals_against_per_game_percentage',
        ),
    ]
