# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineups', '0015_auto_20161221_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameodds',
            name='number_of_goals',
            field=models.CharField(max_length=50),
        ),
    ]
